### ISSUE TITLE
go mod support

### ISSUE THREAD

**Issue by bcho** [kmodules/client-go#307]
Hi, can you provide a go mod spec? Or replace the `github.com/appscode/go-version` dependency with `gomodules.xyz/semver`, as `appscode/go-version`'s go mod package path is incorrect for go mod. Currently, I have to replace this library as follow:

```
replace github.com/appscode/go-version => gomodules.xyz/semver v0.0.0-20190324134429-1dbb5e224a
```

**Comment by tamalsaha** [comment]
We are going to provide Go mod support after Kubernetes 1.15 release which will add Go mod support to Kubernetes client libraries. This is going happen at the end of June.
